/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppTaskflowRouteImport } from './routes/app.taskflow'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoadmapsRouteImport } from './routes/app.roadmaps'
import { Route as AppRitualsRouteImport } from './routes/app.rituals'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPomodoroRouteImport } from './routes/app.pomodoro'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppHydrationRouteImport } from './routes/app.hydration'
import { Route as AppHabitsRouteImport } from './routes/app.habits'
import { Route as AppFocusRouteImport } from './routes/app.focus'
import { Route as AppDailyRouteImport } from './routes/app.daily'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAppearanceRouteImport } from './routes/app.appearance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTaskflowRoute = AppTaskflowRouteImport.update({
  id: '/taskflow',
  path: '/taskflow',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapsRoute = AppRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => AppRoute,
} as any)
const AppRitualsRoute = AppRitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPomodoroRoute = AppPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHydrationRoute = AppHydrationRouteImport.update({
  id: '/hydration',
  path: '/hydration',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyRoute = AppDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/daily': typeof AppDailyRoute
  '/app/focus': typeof AppFocusRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/hydration': typeof AppHydrationRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/pomodoro': typeof AppPomodoroRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rituals': typeof AppRitualsRoute
  '/app/roadmaps': typeof AppRoadmapsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/taskflow': typeof AppTaskflowRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/daily': typeof AppDailyRoute
  '/app/focus': typeof AppFocusRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/hydration': typeof AppHydrationRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/pomodoro': typeof AppPomodoroRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rituals': typeof AppRitualsRoute
  '/app/roadmaps': typeof AppRoadmapsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/taskflow': typeof AppTaskflowRoute
  '/app/tasks': typeof AppTasksRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/appearance': typeof AppAppearanceRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/daily': typeof AppDailyRoute
  '/app/focus': typeof AppFocusRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/hydration': typeof AppHydrationRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/notes': typeof AppNotesRoute
  '/app/pomodoro': typeof AppPomodoroRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rituals': typeof AppRitualsRoute
  '/app/roadmaps': typeof AppRoadmapsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/taskflow': typeof AppTaskflowRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/appearance'
    | '/app/calendar'
    | '/app/daily'
    | '/app/focus'
    | '/app/habits'
    | '/app/hydration'
    | '/app/insights'
    | '/app/library'
    | '/app/notes'
    | '/app/pomodoro'
    | '/app/profile'
    | '/app/rituals'
    | '/app/roadmaps'
    | '/app/settings'
    | '/app/taskflow'
    | '/app/tasks'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/appearance'
    | '/app/calendar'
    | '/app/daily'
    | '/app/focus'
    | '/app/habits'
    | '/app/hydration'
    | '/app/insights'
    | '/app/library'
    | '/app/notes'
    | '/app/pomodoro'
    | '/app/profile'
    | '/app/rituals'
    | '/app/roadmaps'
    | '/app/settings'
    | '/app/taskflow'
    | '/app/tasks'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/appearance'
    | '/app/calendar'
    | '/app/daily'
    | '/app/focus'
    | '/app/habits'
    | '/app/hydration'
    | '/app/insights'
    | '/app/library'
    | '/app/notes'
    | '/app/pomodoro'
    | '/app/profile'
    | '/app/rituals'
    | '/app/roadmaps'
    | '/app/settings'
    | '/app/taskflow'
    | '/app/tasks'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taskflow': {
      id: '/app/taskflow'
      path: '/taskflow'
      fullPath: '/app/taskflow'
      preLoaderRoute: typeof AppTaskflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmaps': {
      id: '/app/roadmaps'
      path: '/roadmaps'
      fullPath: '/app/roadmaps'
      preLoaderRoute: typeof AppRoadmapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rituals': {
      id: '/app/rituals'
      path: '/rituals'
      fullPath: '/app/rituals'
      preLoaderRoute: typeof AppRitualsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pomodoro': {
      id: '/app/pomodoro'
      path: '/pomodoro'
      fullPath: '/app/pomodoro'
      preLoaderRoute: typeof AppPomodoroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hydration': {
      id: '/app/hydration'
      path: '/hydration'
      fullPath: '/app/hydration'
      preLoaderRoute: typeof AppHydrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/habits': {
      id: '/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/focus': {
      id: '/app/focus'
      path: '/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/daily': {
      id: '/app/daily'
      path: '/daily'
      fullPath: '/app/daily'
      preLoaderRoute: typeof AppDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appearance': {
      id: '/app/appearance'
      path: '/appearance'
      fullPath: '/app/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDailyRoute: typeof AppDailyRoute
  AppFocusRoute: typeof AppFocusRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppHydrationRoute: typeof AppHydrationRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPomodoroRoute: typeof AppPomodoroRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRitualsRoute: typeof AppRitualsRoute
  AppRoadmapsRoute: typeof AppRoadmapsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTaskflowRoute: typeof AppTaskflowRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppearanceRoute: AppAppearanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDailyRoute: AppDailyRoute,
  AppFocusRoute: AppFocusRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppHydrationRoute: AppHydrationRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotesRoute: AppNotesRoute,
  AppPomodoroRoute: AppPomodoroRoute,
  AppProfileRoute: AppProfileRoute,
  AppRitualsRoute: AppRitualsRoute,
  AppRoadmapsRoute: AppRoadmapsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTaskflowRoute: AppTaskflowRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
